-- MySQL Script generated by MySQL Workbench
-- sáb 24 ago 2019 14:02:00 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `categoria_id` INT NOT NULL AUTO_INCREMENT,
  `categoria_nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pregunta` (
  `pregunta_id` INT NOT NULL AUTO_INCREMENT,
  `pregunta_tipo` INT NULL,
  `pregunta_texto` VARCHAR(100) NULL,
  `categoria_categoria_id` INT NOT NULL,
  PRIMARY KEY (`pregunta_id`),
  INDEX `fk_pregunta_categoria1_idx` (`categoria_categoria_id` ASC),
  CONSTRAINT `fk_pregunta_categoria1`
    FOREIGN KEY (`categoria_categoria_id`)
    REFERENCES `mydb`.`categoria` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`respuesta_pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`respuesta_pregunta` (
  `respuesta_pregunta_id` INT NOT NULL AUTO_INCREMENT,
  `respuesta_pregunta_texto` VARCHAR(100) NULL,
  `respuesta_pregunta_imagen` VARCHAR(100) NULL,
  `pregunta_id_anidada` INT NULL,
  `pregunta_pregunta_id` INT NOT NULL,
  PRIMARY KEY (`respuesta_pregunta_id`),
  INDEX `fk_respuesta_pregunta_pregunta1_idx` (`pregunta_pregunta_id` ASC),
  CONSTRAINT `fk_respuesta_pregunta_pregunta1`
    FOREIGN KEY (`pregunta_pregunta_id`)
    REFERENCES `mydb`.`pregunta` (`pregunta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`encuestador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`encuestador` (
  `encuestador_dni` INT NOT NULL,
  `encuestador_nombre` VARCHAR(100) NULL,
  `encuestador_contraseña` VARCHAR(100) NULL,
  PRIMARY KEY (`encuestador_dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`encuestado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`encuestado` (
  `encuestado_id` INT NOT NULL AUTO_INCREMENT,
  `encuestado_iniciales` VARCHAR(10) NOT NULL,
  `encuestado_sexo` INT NOT NULL,
  `encuestado_email` VARCHAR(100) NULL,
  `encuestado_telefono` MEDIUMTEXT NOT NULL,
  `encuestado_fecha_nacimiento` DATE NOT NULL,
  `encuestado_nivel_educativo` VARCHAR(100) NOT NULL,
  `encuestado_actividad_laboral` VARCHAR(100) NULL,
  `encuestado_cargo` VARCHAR(100) NULL,
  `encuestado_enfermedad` VARCHAR(100) NULL,
  `encuestado_medicina` VARCHAR(45) NULL,
  `encuestado_suplemento` VARCHAR(100) NULL,
  `encuestado_fumador` INT NOT NULL,
  `encuestado_embarazo` VARCHAR(25) NOT NULL,
  `encuestado_menospausa` INT NOT NULL,
  `encuestado_estado_civil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`encuestado_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`encuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`encuesta` (
  `encuesta_id` INT NOT NULL AUTO_INCREMENT,
  `encuestador_encuestador_dni` INT NOT NULL,
  `encuestado_encuestado_id` INT NOT NULL,
  PRIMARY KEY (`encuesta_id`),
  INDEX `fk_encuesta_encuestador1_idx` (`encuestador_encuestador_dni` ASC),
  INDEX `fk_encuesta_encuestado1_idx` (`encuestado_encuestado_id` ASC),
  CONSTRAINT `fk_encuesta_encuestador1`
    FOREIGN KEY (`encuestador_encuestador_dni`)
    REFERENCES `mydb`.`encuestador` (`encuestador_dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_encuesta_encuestado1`
    FOREIGN KEY (`encuestado_encuestado_id`)
    REFERENCES `mydb`.`encuestado` (`encuestado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`respuesta_encuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`respuesta_encuesta` (
  `respuesta_encuesta_id` INT NOT NULL AUTO_INCREMENT,
  `respuesta_pregunta_respuesta_pregunta_id` INT NOT NULL,
  `encuesta_encuesta_id` INT NOT NULL,
  PRIMARY KEY (`respuesta_encuesta_id`),
  INDEX `fk_respuesta_encuesta_respuesta_pregunta1_idx` (`respuesta_pregunta_respuesta_pregunta_id` ASC),
  INDEX `fk_respuesta_encuesta_encuesta1_idx` (`encuesta_encuesta_id` ASC),
  CONSTRAINT `fk_respuesta_encuesta_respuesta_pregunta1`
    FOREIGN KEY (`respuesta_pregunta_respuesta_pregunta_id`)
    REFERENCES `mydb`.`respuesta_pregunta` (`respuesta_pregunta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuesta_encuesta_encuesta1`
    FOREIGN KEY (`encuesta_encuesta_id`)
    REFERENCES `mydb`.`encuesta` (`encuesta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
