-- MySQL Script generated by MySQL Workbench
-- Sun Aug 25 01:09:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema survey.app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema survey.app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `survey.app` DEFAULT CHARACTER SET utf8 ;
USE `survey.app` ;

-- -----------------------------------------------------
-- Table `survey.app`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey.app`.`categoria` (
  `categoria_id` INT NOT NULL AUTO_INCREMENT,
  `categoria_nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey.app`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey.app`.`pregunta` (
  `pregunta_id` INT NOT NULL AUTO_INCREMENT,
  `pregunta_texto` VARCHAR(255) NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`pregunta_id`),
  INDEX `fk_pregunta_categoria1_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_pregunta_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `survey.app`.`categoria` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey.app`.`respuesta_pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey.app`.`respuesta_pregunta` (
  `respuesta_pregunta_id` INT NOT NULL AUTO_INCREMENT,
  `respuesta_pregunta_texto` VARCHAR(100) NOT NULL,
  `respuesta_pregunta_imagen` VARCHAR(255) NULL,  
  `respuesta_pregunta_excluyente` BOOLEAN NOT NULL,
  `pregunta_id_anidada` INT NULL,
  `pregunta_id` INT NOT NULL,
  `respuesta_pregunta_tipo` INT NOT NULL,
  PRIMARY KEY (`respuesta_pregunta_id`),
  INDEX `fk_respuesta_pregunta_pregunta1_idx` (`pregunta_id` ASC),
  CONSTRAINT `fk_respuesta_pregunta_pregunta1`
    FOREIGN KEY (`pregunta_id`)
    REFERENCES `survey.app`.`pregunta` (`pregunta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey.app`.`encuestador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey.app`.`encuestador` (
  `encuestador_dni` INT NOT NULL,
  `encuestador_nombre` VARCHAR(100) NOT NULL,
  `encuestador_pass` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`encuestador_dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey.app`.`encuestado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey.app`.`encuestado` (
  `encuestado_id` INT NOT NULL AUTO_INCREMENT,
  `encuestado_iniciales` VARCHAR(10) NOT NULL,
  `encuestado_sexo` INT NOT NULL,
  `encuestado_email` VARCHAR(100) NULL,
  `encuestado_telefono` BIGINT NOT NULL,
  `encuestado_fecha_nacimiento` DATE NOT NULL,
  `encuestado_nivel_educativo` VARCHAR(50) NOT NULL,
  `encuestado_actividad_laboral` VARCHAR(50) NULL,
  `encuestado_cargo` VARCHAR(50) NULL,
  `encuestado_enfermedad` VARCHAR(50) NULL,
  `encuestado_medicina` VARCHAR(45) NULL,
  `encuestado_suplemento` VARCHAR(50) NULL,
  `encuestado_fumador` INT NULL,
  `encuestado_embarazo` VARCHAR(25) NULL,
  `encuestado_menopausia` INT NULL,
  `encuestado_lactando` INT NULL,
  `encuestado_estado_civil` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`encuestado_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey.app`.`encuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey.app`.`encuesta` (
  `encuesta_id` INT NOT NULL AUTO_INCREMENT,
  `encuestador_dni` INT NOT NULL,
  `encuestado_id` INT NOT NULL,
  PRIMARY KEY (`encuesta_id`),
  INDEX `fk_encuesta_encuestador1_idx` (`encuestador_dni` ASC),
  INDEX `fk_encuesta_encuestado1_idx` (`encuestado_id` ASC),
  CONSTRAINT `fk_encuesta_encuestador1`
    FOREIGN KEY (`encuestador_dni`)
    REFERENCES `survey.app`.`encuestador` (`encuestador_dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_encuesta_encuestado1`
    FOREIGN KEY (`encuestado_id`)
    REFERENCES `survey.app`.`encuestado` (`encuestado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey.app`.`respuesta_encuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey.app`.`respuesta_encuesta` (
  `respuesta_encuesta_id` INT NOT NULL AUTO_INCREMENT,
  `respuesta_pregunta_id` INT NOT NULL,
  `encuesta_id` INT NOT NULL,
  PRIMARY KEY (`respuesta_encuesta_id`),
  INDEX `fk_respuesta_encuesta_respuesta_pregunta1_idx` (`respuesta_pregunta_id` ASC),
  INDEX `fk_respuesta_encuesta_encuesta1_idx` (`encuesta_id` ASC),
  CONSTRAINT `fk_respuesta_encuesta_respuesta_pregunta1`
    FOREIGN KEY (`respuesta_pregunta_id`)
    REFERENCES `survey.app`.`respuesta_pregunta` (`respuesta_pregunta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuesta_encuesta_encuesta1`
    FOREIGN KEY (`encuesta_id`)
    REFERENCES `survey.app`.`encuesta` (`encuesta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
